import { HttpApi } from '../../utils/helpers';
import { SymbolConversion } from '../../utils/symbolConversion';
import { Hyperliquid } from '../../index';
import type { AllMids, BuilderFeeApproval, CandleSnapshot, Delegation, DelegatorHistoryEntry, DelegatorReward, DelegatorSummary, ExtraAgent, FrontendOpenOrders, HistoricalOrder, L2Book, LegalCheck, MultiSigSigners, OrderStatus, PortfolioPeriods, PreTransferCheck, Referral, SubAccount, TwapHistory, TwapSliceFill, UserFees, UserFills, UserOpenOrders, UserOrderHistory, UserRateLimit, UserRole, ValidatorSummary, VaultDetails, VaultEquity, VaultSummary } from '../../types';
export declare class GeneralInfoAPI {
    private httpApi;
    private symbolConversion;
    private parent;
    constructor(httpApi: HttpApi, symbolConversion: SymbolConversion, parent: Hyperliquid);
    getAllMids(rawResponse?: boolean): Promise<AllMids>;
    getUserOpenOrders(user: string, rawResponse?: boolean): Promise<UserOpenOrders>;
    getFrontendOpenOrders(user: string, rawResponse?: boolean): Promise<FrontendOpenOrders>;
    getUserFills(user: string, rawResponse?: boolean): Promise<UserFills>;
    getUserFillsByTime(user: string, startTime: number, endTime?: number, rawResponse?: boolean): Promise<UserFills>;
    getUserRateLimit(user: string, rawResponse?: boolean): Promise<UserRateLimit>;
    getOrderStatus(user: string, oid: number | string, rawResponse?: boolean): Promise<OrderStatus>;
    getL2Book(coin: string, rawResponse?: boolean, nSigFigs?: number, mantissa?: number): Promise<L2Book>;
    getCandleSnapshot(coin: string, interval: string, startTime: number, endTime: number, rawResponse?: boolean): Promise<CandleSnapshot>;
    getMaxBuilderFee(user: string, builder: string, rawResponse?: boolean): Promise<number>;
    getHistoricalOrders(user: string, rawResponse?: boolean): Promise<HistoricalOrder[]>;
    getUserTwapSliceFills(user: string, rawResponse?: boolean): Promise<TwapSliceFill[]>;
    getSubAccounts(user: string, rawResponse?: boolean): Promise<SubAccount[]>;
    getVaultDetails(vaultAddress: string, user?: string, rawResponse?: boolean): Promise<VaultDetails>;
    getUserVaultEquities(user: string, rawResponse?: boolean): Promise<VaultEquity[]>;
    getUserRole(user: string, rawResponse?: boolean): Promise<UserRole>;
    getDelegations(user: string, rawResponse?: boolean): Promise<Delegation[]>;
    getDelegatorSummary(user: string, rawResponse?: boolean): Promise<DelegatorSummary>;
    getDelegatorHistory(user: string, rawResponse?: boolean): Promise<DelegatorHistoryEntry[]>;
    getDelegatorRewards(user: string, rawResponse?: boolean): Promise<DelegatorReward[]>;
    validatorSummaries(rawResponse?: boolean): Promise<ValidatorSummary[]>;
    vaultSummaries(rawResponse?: boolean): Promise<VaultSummary[]>;
    userFees(user: string, rawResponse?: boolean): Promise<UserFees>;
    portfolio(user: string, rawResponse?: boolean): Promise<PortfolioPeriods>;
    preTransferCheck(user: string, source: string, rawResponse?: boolean): Promise<PreTransferCheck>;
    referral(user: string, rawResponse?: boolean): Promise<Referral>;
    extraAgents(user: string, rawResponse?: boolean): Promise<ExtraAgent[]>;
    isVip(user: string, rawResponse?: boolean): Promise<boolean>;
    legalCheck(user: string, rawResponse?: boolean): Promise<LegalCheck>;
    userTwapSliceFillsByTime(user: string, startTime: number, endTime?: number, aggregateByTime?: boolean, rawResponse?: boolean): Promise<TwapSliceFill[]>;
    twapHistory(user: string, rawResponse?: boolean): Promise<TwapHistory[]>;
    userToMultiSigSigners(user: string, rawResponse?: boolean): Promise<MultiSigSigners | null>;
    getBuilderFeeApproval(user: string, builderAddress: string, rawResponse?: boolean): Promise<BuilderFeeApproval>;
    getUserOrderHistory(user: string, startTime: number, endTime?: number, rawResponse?: boolean): Promise<UserOrderHistory>;
}
//# sourceMappingURL=general.d.ts.map